steps:
  - id: "build wordpress image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/wordpress:${SHORT_SHA}", "."]
  - id: "push wordpress image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/wordpress:${SHORT_SHA}"]
  - id: "update service.yaml"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: "bash"
    args:
      - "-c"
      - sed -i "s|IMAGE_URL_PLACEHOLDER|gcr.io/${PROJECT_ID}/wordpress:${SHORT_SHA}|g" service.yaml;
  - id: "deploy wordpress service"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', "services", "replace", "service.yaml"]
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - "gcr.io/${PROJECT_ID}/wordpress:${SHORT_SHA}"
