version: '3.1'

services:
  wordpress:
    image: wordpress
    platform: "linux/amd64"
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html:rw
      - ./:/work
    links:
      - db:mysql
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: really_strong_password

  db:
    image: mysql:8.0
    platform: "linux/amd64"
    restart: always
    volumes:
      ## - ./local/initdb.d:/docker-entrypoint-initdb.d:ro
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: really_strong_password
      MYSQL_USER: wordpress
      MYSQL_ROOT_PASSWORD: really_strong_password

  proxy:
    image: localhost/proxy:local
    build:
      context: proxy
      dockerfile: Dockerfile
    platform: "linux/amd64"
    env_file:
      - secrets/wordpress.env
    command: cloud-sql-proxy --unix-socket /cloudsql/ portal-twbc-org:us-west1:joomla-db 
    volumes:
      - cloudsql:/cloudsql
      - root:/root:rw

  admin:
    image: phpmyadmin
    restart: always
    links:
      - db:mysql
    ports:
      - 8085:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: really_strong_password

volumes:
  dbdata: {}
  cloudsql: {}
  root: {}
