version: '3.1'

services:
  wordpress:
    image: wordpress
    platform: "linux/amd64"
    restart: always
    ports:
      - 8080:80
    volumes:
      - cloudsql:/cloudsql
      - ./html:/var/www/html:rw
      - ./:/work
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    depends_on:
      - proxy

  proxy:
    image: local/proxy:local
    build:
      context: proxy
      dockerfile: Dockerfile
    platform: "linux/amd64"
    env_file:
      - secrets/wordpress.env
    command: cloud-sql-proxy --unix-socket /cloudsql/ wordpress-test-434320:us-west1:wordpress
    volumes:
      - cloudsql:/cloudsql
      - root:/root:rw

  admin:
    image: phpmyadmin
    restart: always
    platform: "linux/amd64"
    ports:
      - 8085:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: localhost
      PMA_SOCKET: /cloudsql/wordpress-test-434320:us-west1:wordpress
      PMA_USER: ${WORDPRESS_DB_USER}
      PMA_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - cloudsql:/cloudsql
    depends_on:
      - proxy

volumes:
  dbdata: {}
  cloudsql: {}
  root: {}
